[package]
name = "poly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
lazy_static = "1.4.0"
test-case = "2.2.2"

[dev-dependencies]
pretty_assertions = "1.0.0"
